import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import Header from './ui/header'
import Footer from './ui/footer'
import './globals.css'

const dmSans = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased bg-[--background]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
